# =============================================================================
# Prometheus Configuration for FHIR Bridge Database Monitoring
# =============================================================================
# This configuration sets up scraping for PostgreSQL metrics and alerting
# =============================================================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: '${ENVIRONMENT:-local}'
    service: 'fhir-bridge'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "postgres-alerts.yml"

# Scrape configurations
scrape_configs:
  # PostgreSQL metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s
    params:
      collect[]:
        - pg_stat_database
        - pg_stat_user_tables
        - pg_stat_user_indexes
        - pg_statio_user_tables
        - pg_stat_bgwriter
        - pg_stat_replication
        - pg_settings
        - pg_locks
        - pg_stat_activity

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: /metrics
    scrape_interval: 30s

  # Application metrics (if available)
  - job_name: 'fhir-bridge-app'
    static_configs:
      - targets: ['fhir-bridge:8081']
    metrics_path: /actuator/prometheus
    scrape_interval: 30s
    scrape_timeout: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 30s