# =============================================================================
# Development Profile Configuration for FHIR Bridge
# =============================================================================

spring:
  # Database configuration for development
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fhir_bridge}
    username: ${DB_USERNAME:fhir_user}
    password: ${DB_PASSWORD:fhir_password}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 900000
      leak-detection-threshold: 30000
      pool-name: FhirBridgeDevPool
  
  jpa:
    hibernate:
      ddl-auto: update  # Allow schema updates in development
    show-sql: true      # Show SQL queries in development
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        generate_statistics: false
        jdbc:
          batch_size: 10
          fetch_size: 50
  
  # Redis configuration for development
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  # Security configuration for development
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080/auth}

# Management endpoints - more permissive in development
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    metrics:
      enabled: true
    loggers:
      enabled: true
  server:
    port: 8081

# Logging configuration for development
logging:
  level:
    com.bridge: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data.redis: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/fhir-bridge-dev.log

# Application-specific configuration for development
fhir-bridge:
  transformation:
    timeout: 60s  # Longer timeout for development/debugging
    validation:
      strict: false  # Less strict validation in development
  consent:
    cache-ttl: 60s  # Shorter cache TTL for development
    default-policy: ALLOW  # More permissive default for development
  audit:
    enabled: true
    level: DEBUG
  security:
    cors:
      allowed-origins: 
        - "http://localhost:3000"
        - "http://localhost:8080"
        - "http://localhost:8081"
      allowed-methods: 
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers: "*"
      allow-credentials: true
  
# Development-specific features
debug: true
trace: false

# Server configuration
server:
  port: 8080
  error:
    include-stacktrace: always
    include-message: always
    include-binding-errors: always