# =============================================================================
# Test Profile Configuration for FHIR Bridge
# =============================================================================

spring:
  # Database configuration for testing
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fhir_bridge_test}
    username: ${DB_USERNAME:fhir_test_user}
    password: ${DB_PASSWORD:fhir_test_password}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 10000
      idle-timeout: 180000
      max-lifetime: 600000
      pool-name: FhirBridgeTestPool
  
  jpa:
    hibernate:
      ddl-auto: create-drop  # Recreate schema for each test run
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
        jdbc:
          batch_size: 5
          fetch_size: 25
  
  # Redis configuration for testing
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 1000ms
      database: 1  # Use different database for tests
  
  # Security configuration for testing
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080/auth}

# Management endpoints for testing
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging configuration for testing
logging:
  level:
    com.bridge: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.springframework.test: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Application-specific configuration for testing
fhir-bridge:
  transformation:
    timeout: 10s
    validation:
      strict: true
  consent:
    cache-ttl: 10s
    default-policy: DENY  # More restrictive for testing
  audit:
    enabled: true
    level: INFO
  security:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"

# Test-specific configuration
test:
  database:
    cleanup: true
    seed-data: true
  cache:
    flush-between-tests: true
  security:
    mock-authentication: true

# Server configuration for testing
server:
  port: 0  # Use random port for testing
  error:
    include-stacktrace: never
    include-message: always