spring:
  application:
    name: fhir-bridge
  
  # Database configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fhir_bridge}
    username: ${DB_USERNAME:fhir_user}
    password: ${DB_PASSWORD:fhir_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:20}
      minimum-idle: ${DB_MIN_IDLE:5}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${DB_IDLE_TIMEOUT:600000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}
      leak-detection-threshold: ${DB_LEAK_DETECTION:60000}
      pool-name: FhirBridgePool
      connection-test-query: SELECT 1
      validation-timeout: 5000
      initialization-fail-timeout: 0
  # Database health check
  sql:
    init:
      mode: ${DB_INIT_MODE:never}
      continue-on-error: false
  
  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    clean-disabled: true
    repair: true
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          batch_size: 25
          fetch_size: 100
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        generate_statistics: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 1000
  
  # Redis configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
  
  # Security configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:}
          jwk-set-uri: ${JWT_JWK_SET_URI:}
          audiences: ${JWT_AUDIENCES:fhir-bridge-api}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:defaultSecretKeyThatShouldBeReplacedInProduction}
  access-token-expiration-minutes: ${JWT_ACCESS_TOKEN_EXPIRATION:15}
  refresh-token-expiration-days: ${JWT_REFRESH_TOKEN_EXPIRATION:7}
  issuer: ${JWT_ISSUER:fhir-bridge}
  audience: ${JWT_AUDIENCE:fhir-bridge-api}
  clock-skew-seconds: ${JWT_CLOCK_SKEW:60}

# OAuth2 Configuration
oauth2:
  token-endpoint: ${OAUTH2_TOKEN_ENDPOINT:https://auth.fhirbridge.com/oauth2/token}
  client-id: ${OAUTH2_CLIENT_ID:fhir-bridge-client}
  client-secret: ${OAUTH2_CLIENT_SECRET:}
  authorization-endpoint: ${OAUTH2_AUTH_ENDPOINT:https://auth.fhirbridge.com/oauth2/authorize}
  user-info-endpoint: ${OAUTH2_USER_INFO_ENDPOINT:https://auth.fhirbridge.com/oauth2/userinfo}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: ${ENVIRONMENT:production}
    web:
      server:
        request:
          autotime:
            enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 100ms,500ms,1s,2s,5s
  health:
    db:
      enabled: true
    redis:
      enabled: true
    diskspace:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

# Logging configuration
logging:
  level:
    com.bridge: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.cache: INFO
    org.springframework.data.redis: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    level: "%5p"
  file:
    name: logs/fhir-bridge.log
    max-size: 100MB
    max-history: 30
    total-size-cap: 3GB
  structured:
    format:
      console: json
      file: json

# Application-specific configuration
fhir-bridge:
  transformation:
    timeout: 30s
    validation:
      strict: true
      profiles:
        - "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"
        - "http://hl7.org/fhir/us/core/StructureDefinition/us-core-encounter"
        - "http://hl7.org/fhir/us/core/StructureDefinition/us-core-observation-lab"
    cache:
      enabled: true
      ttl: 1h
      max-size: 1000
  consent:
    cache-ttl: 300s
    default-policy: DENY
    categories:
      - "medical-records"
      - "lab-results"
      - "imaging"
      - "demographics"
  audit:
    enabled: true
    level: INFO
    retention-days: 90
    anonymize: true
  fhir:
    server:
      enabled: true
      base-url: ${FHIR_SERVER_BASE_URL:https://hapi.fhir.org/baseR4}
      timeout: 30s
      max-connections: 50
      retry-attempts: 3
    validation:
      enabled: true
      fail-on-warning: false
    profiles:
      us-core: "http://hl7.org/fhir/us/core/"
      carin-bb: "http://hl7.org/fhir/us/carin-bb/"
  security:
    cors:
      enabled: true
    rate-limiting:
      enabled: true
      requests-per-minute: 1000
      burst-capacity: 100
  monitoring:
    health-checks:
      enabled: true
      interval: 30s
    metrics:
      enabled: true
      export-prometheus: true