name: Deploy Dev Stack
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-east-1

permissions:
  id-token: write      # OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/github-oidc-tefca
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform init
        run: terraform -chdir=infra init

      - name: Terraform plan
        run: terraform -chdir=infra plan -no-color -out=tfplan

      - name: Terraform apply
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=infra apply tfplan